# Generated by Django 5.0.6 on 2024-06-05 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mini_Category',
            new_name='MiniCategory',
        ),
        migrations.RenameIndex(
            model_name='minicategory',
            new_name='market_mini_name_6c7633_idx',
            old_name='market_mini_name_bdfd29_idx',
        ),
    ]
