# Generated by Django 5.0.6 on 2024-06-07 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_market'),
        ('market', '0005_product_category'),
    ]

    operations = [
    ]
