# Generated by Django 5.0.6 on 2024-06-10 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_delete_chatmessage'),
        ('market', '0008_alter_product_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Market',
        ),
    ]
