# Generated by Django 5.0.6 on 2024-06-14 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_alter_minicategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minicategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.category'),
        ),
    ]
