# Generated by Django 4.2.7 on 2024-06-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
