# Generated by Django 5.0.6 on 2024-06-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_delete_chatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AddField(
            model_name='message',
            name='room_name',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
