# Generated by Django 5.0.6 on 2024-06-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_rename_content_message_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room_name',
            field=models.CharField(default='default_room_name', max_length=255),
        ),
    ]
