# Generated by Django 5.0.6 on 2024-06-18 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_message_user'),
        ('market', '0017_remove_product_address_remove_product_zipcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='market.product'),
        ),
    ]
