# Generated by Django 5.0.6 on 2024-06-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_message_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.AlterField(
            model_name='message',
            name='room_name',
            field=models.CharField(default='default_room_name', max_length=255),
        ),
    ]
